name: SAST
on:
  pull_request:
jobs:
  sast:
    name: semgrep-oss/scan
    runs-on: ubuntu-latest
    container:
      image: semgrep/semgrep
    steps:
      - uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7
      - name: Scan
        shell: bash
        run: |
          semgrep scan --config auto --error --verbose \
            --exclude-rule yaml.docker-compose.security.no-new-privileges.no-new-privileges \
            --exclude-rule yaml.docker-compose.security.writable-filesystem-service.writable-filesystem-service \
            --exclude-rule terraform.aws.security.aws-dynamodb-table-unencrypted.aws-dynamodb-table-unencrypted
